name: Build and Release RPM

on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install RPM build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y rpm
        mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

    - name: Prepare files
      run: |
        cp -r ./kafka-tools ~/rpmbuild/SOURCES/
        cd ~/rpmbuild/SOURCES/
        tar czvf kafka-tools-${GITHUB_REF##*/}.tar.gz kafka-tools

    - name: Create spec file
      run: |
        echo "Name:           kafka-tools" > ~/rpmbuild/SPECS/kafka-tools.spec
        echo "Version:        ${GITHUB_REF##*/}" >> ~/rpmbuild/SPECS/kafka-tools.spec
        echo "Release:        1%{?dist}" >> ~/rpmbuild/SPECS/kafka-tools.spec
        echo "Summary:        Your package summary here" >> ~/rpmbuild/SPECS/kafka-tools.spec
        echo "Group:          Applications/Internet" >> ~/rpmbuild/SPECS/kafka-tools.spec
        echo "License:        Your license here" >> ~/rpmbuild/SPECS/kafka-tools.spec
        echo "URL:            http://example.com" >> ~/rpmbuild/SPECS/kafka-tools.spec
        echo "Source0:        %{name}-%{version}.tar.gz" >> ~/rpmbuild/SPECS/kafka-tools.spec
        echo "%description" >> ~/rpmbuild/SPECS/kafka-tools.spec
        echo "Your package description here." >> ~/rpmbuild/SPECS/kafka-tools.spec
        echo "%prep" >> ~/rpmbuild/SPECS/kafka-tools.spec
        echo "%setup -q" >> ~/rpmbuild/SPECS/kafka-tools.spec
        echo "%build" >> ~/rpmbuild/SPECS/kafka-tools.spec
        echo "# Add build commands if necessary" >> ~/rpmbuild/SPECS/kafka-tools.spec
        echo "%install" >> ~/rpmbuild/SPECS/kafka-tools.spec
        echo "rm -rf $RPM_BUILD_ROOT" >> ~/rpmbuild/SPECS/kafka-tools.spec
        echo "mkdir -p $RPM_BUILD_ROOT/opt/%{name}" >> ~/rpmbuild/SPECS/kafka-tools.spec
        echo "cp -r * $RPM_BUILD_ROOT/opt/%{name}" >> ~/rpmbuild/SPECS/kafka-tools.spec
        echo "%clean" >> ~/rpmbuild/SPECS/kafka-tools.spec
        echo "rm -rf $RPM_BUILD_ROOT" >> ~/rpmbuild/SPECS/kafka-tools.spec
        echo "%files" >> ~/rpmbuild/SPECS/kafka-tools.spec
        echo "%defattr(-,root,root,-)" >> ~/rpmbuild/SPECS/kafka-tools.spec
        echo "/opt/%{name}" >> ~/rpmbuild/SPECS/kafka-tools.spec
        echo "%changelog" >> ~/rpmbuild/SPECS/kafka-tools.spec
        # Add changelog entries if necessary

    - name: Build RPM
      run: rpmbuild -ba ~/rpmbuild/SPECS/kafka-tools.spec

    - name: Publish RPM as Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ~/rpmbuild/RPMS/noarch/kafka-tools-${GITHUB_REF##*/}-1.noarch.rpm
        token: ${{ secrets.GITHUB_TOKEN }}

